use std::path::Path;
use std::{env, fs};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")?;
    let out_dir = env::var("OUT_DIR")?;

    generate_product_includes(&manifest_dir, &out_dir)?;
    generate_sunspec_models(&manifest_dir, &out_dir)?;

    Ok(())
}

fn generate_product_includes(
    manifest_dir: &str,
    out_dir: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let products_dir = Path::new(manifest_dir).join("src/products");
    let dest = Path::new(out_dir).join("product_includes.rs");

    println!("cargo:rerun-if-changed=src/products");

    let mut entries: Vec<String> = fs::read_dir(&products_dir)?
        .filter_map(|e| e.ok())
        .filter_map(|e| {
            let path = e.path();
            if path.extension().and_then(|x| x.to_str()) == Some("json") {
                path.file_name()?.to_str().map(String::from)
            } else {
                None
            }
        })
        .collect();

    entries.sort();

    let includes: Vec<String> = entries
        .iter()
        .map(|name| {
            let abs = products_dir.join(name);
            format!("    include_str!({:?}),", abs.to_string_lossy())
        })
        .collect();

    let generated = format!(
        "// Auto-generated by build.rs — do not edit\n&[\n{}\n]",
        includes.join("\n")
    );

    fs::write(&dest, generated)?;
    Ok(())
}

fn generate_sunspec_models(
    manifest_dir: &str,
    out_dir: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let sunspec_dir = Path::new(manifest_dir).join("src/sunspec/models/json");
    let dest = Path::new(out_dir).join("sunspec_models.rs");

    println!("cargo:rerun-if-changed=src/sunspec/models/json");

    let mut entries: Vec<(u16, String)> = fs::read_dir(&sunspec_dir)?
        .filter_map(|e| e.ok())
        .filter_map(|e| {
            let path = e.path();
            let name = path.file_name()?.to_str()?;
            if !name.starts_with("model_") || !name.ends_with(".json") {
                return None;
            }
            let id_str = name.strip_prefix("model_")?.strip_suffix(".json")?;
            let id: u16 = id_str.parse().ok()?;
            Some((id, path.to_string_lossy().to_string()))
        })
        .collect();

    entries.sort_by_key(|(id, _)| *id);

    let mut lines = vec![
        "// Auto-generated by build.rs — do not edit".to_string(),
        "pub static SUNSPEC_MODELS: &[(u16, &str)] = &[".to_string(),
    ];

    for (id, path) in entries {
        lines.push(format!("    ({id}, include_str!(\"{path}\")),"));
    }

    lines.push("];".to_string());
    fs::write(&dest, lines.join("\n"))?;
    Ok(())
}
